import express from "express";
import { getMyNotifications, markAsRead, markAllAsRead, getUnreadCount } from "../../controllers/notifications/notificationsController.js";
import authMiddleware from "../../middlewares/authMiddleware.js";
const router = express.Router();
router.use(authMiddleware);
router.get("/",           getMyNotifications);
router.get("/unread-count", getUnreadCount);
router.put("/:id/read",   markAsRead);
router.put("/read-all",   markAllAsRead);
export default router;
